export { default as Home } from './Home'
export { default as Logo } from './Logo'
export { default as Map } from './Map'
export { default as Puzzle } from './Puzzle'
export { default as Setting } from './Setting'
export { default as World } from './World'
export { default as Icon } from './Icon'
